name: Schedule commit to rebuild page on gatsby cloud

# Controls when the action will run. Triggers the workflow on schedule

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "33 17 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs commands using the runners shell
      - name: Run the python script
        run: |
          cd log
          python update_log.py
          cd ../
      - name: Commit files # transfer the new html files back into the repository
        run: |
          git config --local user.name  ${{ github.actor }}
          git add .
          git commit -m "Updating log file"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
